package com.tribbloids.spookystuff

object DebugOldPath
    extends ClasspathDebugger(
      """
  |/home/peng/.m2/repository/aopalliance/aopalliance/1.0/aopalliance-1.0.jar	System Classpath
  |/home/peng/.m2/repository/com/carrotsearch/hppc/0.7.2/hppc-0.7.2.jar	System Classpath
  |/home/peng/.m2/repository/com/chuusai/shapeless_2.12/2.3.2/shapeless_2.12-2.3.2.jar	System Classpath
  |/home/peng/.m2/repository/com/clearspring/analytics/stream/2.7.0/stream-2.7.0.jar	System Classpath
  |/home/peng/.m2/repository/com/esotericsoftware/kryo-shaded/4.0.2/kryo-shaded-4.0.2.jar	System Classpath
  |/home/peng/.m2/repository/com/esotericsoftware/minlog/1.3.0/minlog-1.3.0.jar	System Classpath
  |/home/peng/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.10/jackson-annotations-2.9.10.jar	System Classpath
  |/home/peng/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.10/jackson-core-2.9.10.jar	System Classpath
  |/home/peng/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.10.5/jackson-databind-2.9.10.5.jar	System Classpath
  |/home/peng/.m2/repository/com/fasterxml/jackson/module/jackson-module-paranamer/2.9.10/jackson-module-paranamer-2.9.10.jar	System Classpath
  |/home/peng/.m2/repository/com/fasterxml/jackson/module/jackson-module-scala_2.12/2.9.10/jackson-module-scala_2.12-2.9.10.jar	System Classpath
  |/home/peng/.m2/repository/com/github/fommil/netlib/core/1.1.2/core-1.1.2.jar	System Classpath
  |/home/peng/.m2/repository/com/github/luben/zstd-jni/1.4.4-3/zstd-jni-1.4.4-3.jar	System Classpath
  |/home/peng/.m2/repository/com/github/mutcianm/ascii-graphs_2.12/0.0.6/ascii-graphs_2.12-0.0.6.jar	System Classpath
  |/home/peng/.m2/repository/com/github/rwl/jtransforms/2.4.0/jtransforms-2.4.0.jar	System Classpath
  |/home/peng/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar	System Classpath
  |/home/peng/.m2/repository/com/google/code/gson/gson/2.2.4/gson-2.2.4.jar	System Classpath
  |/home/peng/.m2/repository/com/google/guava/guava/16.0.1/guava-16.0.1.jar	System Classpath
  |/home/peng/.m2/repository/com/google/inject/extensions/guice-servlet/3.0/guice-servlet-3.0.jar	System Classpath
  |/home/peng/.m2/repository/com/google/inject/guice/3.0/guice-3.0.jar	System Classpath
  |/home/peng/.m2/repository/com/google/protobuf/protobuf-java/2.5.0/protobuf-java-2.5.0.jar	System Classpath
  |/home/peng/.m2/repository/com/googlecode/juniversalchardet/juniversalchardet/1.0.3/juniversalchardet-1.0.3.jar	System Classpath
  |/home/peng/.m2/repository/com/ibm/icu/icu4j/59.1/icu4j-59.1.jar	System Classpath
  |/home/peng/.m2/repository/com/lihaoyi/fastparse_2.12/2.1.0/fastparse_2.12-2.1.0.jar	System Classpath
  |/home/peng/.m2/repository/com/lihaoyi/sourcecode_2.12/0.1.5/sourcecode_2.12-0.1.5.jar	System Classpath
  |/home/peng/.m2/repository/com/ning/compress-lzf/1.0.3/compress-lzf-1.0.3.jar	System Classpath
  |/home/peng/.m2/repository/com/openhtmltopdf/openhtmltopdf-core/1.0.0/openhtmltopdf-core-1.0.0.jar	System Classpath
  |/home/peng/.m2/repository/com/openhtmltopdf/openhtmltopdf-jsoup-dom-converter/1.0.0/openhtmltopdf-jsoup-dom-converter-1.0.0.jar	System Classpath
  |/home/peng/.m2/repository/com/openhtmltopdf/openhtmltopdf-pdfbox/1.0.0/openhtmltopdf-pdfbox-1.0.0.jar	System Classpath
  |/home/peng/.m2/repository/com/openhtmltopdf/openhtmltopdf-rtl-support/1.0.0/openhtmltopdf-rtl-support-1.0.0.jar	System Classpath
  |/home/peng/.m2/repository/com/profesorfalken/WMI4Java/1.6.3/WMI4Java-1.6.3.jar	System Classpath
  |/home/peng/.m2/repository/com/profesorfalken/jPowerShell/3.0/jPowerShell-3.0.jar	System Classpath
  |/home/peng/.m2/repository/com/syncthemall/boilerpipe/1.2.2/boilerpipe-1.2.2.jar	System Classpath
  |/home/peng/.m2/repository/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.jar	System Classpath
  |/home/peng/.m2/repository/com/tribbloids/spookystuff/repackaged-selenium-bundle/4.1.4/repackaged-selenium-bundle-4.1.4.jar	System Classpath
  |/home/peng/.m2/repository/com/twitter/chill-java/0.9.3/chill-java-0.9.3.jar	System Classpath
  |/home/peng/.m2/repository/com/twitter/chill_2.12/0.9.3/chill_2.12-0.9.3.jar	System Classpath
  |/home/peng/.m2/repository/com/univocity/univocity-parsers/2.7.3/univocity-parsers-2.7.3.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-all/0.62.2/flexmark-all-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-abbreviation/0.62.2/flexmark-ext-abbreviation-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-admonition/0.62.2/flexmark-ext-admonition-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-anchorlink/0.62.2/flexmark-ext-anchorlink-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-aside/0.62.2/flexmark-ext-aside-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-attributes/0.62.2/flexmark-ext-attributes-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-autolink/0.62.2/flexmark-ext-autolink-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-definition/0.62.2/flexmark-ext-definition-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-emoji/0.62.2/flexmark-ext-emoji-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-enumerated-reference/0.62.2/flexmark-ext-enumerated-reference-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-escaped-character/0.62.2/flexmark-ext-escaped-character-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-footnotes/0.62.2/flexmark-ext-footnotes-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-issues/0.62.2/flexmark-ext-gfm-issues-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-strikethrough/0.62.2/flexmark-ext-gfm-strikethrough-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-tasklist/0.62.2/flexmark-ext-gfm-tasklist-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-gfm-users/0.62.2/flexmark-ext-gfm-users-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-gitlab/0.62.2/flexmark-ext-gitlab-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-ins/0.62.2/flexmark-ext-ins-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-jekyll-front-matter/0.62.2/flexmark-ext-jekyll-front-matter-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-jekyll-tag/0.62.2/flexmark-ext-jekyll-tag-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-macros/0.62.2/flexmark-ext-macros-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-media-tags/0.62.2/flexmark-ext-media-tags-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-superscript/0.62.2/flexmark-ext-superscript-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-tables/0.62.2/flexmark-ext-tables-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-toc/0.62.2/flexmark-ext-toc-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-typographic/0.62.2/flexmark-ext-typographic-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-wikilink/0.62.2/flexmark-ext-wikilink-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-xwiki-macros/0.62.2/flexmark-ext-xwiki-macros-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-yaml-front-matter/0.62.2/flexmark-ext-yaml-front-matter-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-ext-youtube-embedded/0.62.2/flexmark-ext-youtube-embedded-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-html2md-converter/0.62.2/flexmark-html2md-converter-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-jira-converter/0.62.2/flexmark-jira-converter-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-pdf-converter/0.62.2/flexmark-pdf-converter-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-profile-pegdown/0.62.2/flexmark-profile-pegdown-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-util-ast/0.62.2/flexmark-util-ast-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-util-builder/0.62.2/flexmark-util-builder-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-util-collection/0.62.2/flexmark-util-collection-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-util-data/0.62.2/flexmark-util-data-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-util-dependency/0.62.2/flexmark-util-dependency-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-util-format/0.62.2/flexmark-util-format-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-util-html/0.62.2/flexmark-util-html-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-util-misc/0.62.2/flexmark-util-misc-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-util-options/0.62.2/flexmark-util-options-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-util-sequence/0.62.2/flexmark-util-sequence-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-util-visitor/0.62.2/flexmark-util-visitor-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-util/0.62.2/flexmark-util-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark-youtrack-converter/0.62.2/flexmark-youtrack-converter-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vladsch/flexmark/flexmark/0.62.2/flexmark-0.62.2.jar	System Classpath
  |/home/peng/.m2/repository/com/vlkan/flatbuffers/1.2.0-3f79e055/flatbuffers-1.2.0-3f79e055.jar	System Classpath
  |/home/peng/.m2/repository/commons-beanutils/commons-beanutils/1.7.0/commons-beanutils-1.7.0.jar	System Classpath
  |/home/peng/.m2/repository/commons-cli/commons-cli/1.2/commons-cli-1.2.jar	System Classpath
  |/home/peng/.m2/repository/commons-codec/commons-codec/1.3/commons-codec-1.3.jar	System Classpath
  |/home/peng/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar	System Classpath
  |/home/peng/.m2/repository/commons-configuration/commons-configuration/1.6/commons-configuration-1.6.jar	System Classpath
  |/home/peng/.m2/repository/commons-digester/commons-digester/1.8/commons-digester-1.8.jar	System Classpath
  |/home/peng/.m2/repository/commons-httpclient/commons-httpclient/3.1/commons-httpclient-3.1.jar	System Classpath
  |/home/peng/.m2/repository/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar	System Classpath
  |/home/peng/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar	System Classpath
  |/home/peng/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar	System Classpath
  |/home/peng/.m2/repository/commons-net/commons-net/3.1/commons-net-3.1.jar	System Classpath
  |/home/peng/.m2/repository/de/rototor/pdfbox/graphics2d/0.24/graphics2d-0.24.jar	System Classpath
  |/home/peng/.m2/repository/io/airlift/aircompressor/0.10/aircompressor-0.10.jar	System Classpath
  |/home/peng/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.5/metrics-core-3.1.5.jar	System Classpath
  |/home/peng/.m2/repository/io/dropwizard/metrics/metrics-graphite/3.1.5/metrics-graphite-3.1.5.jar	System Classpath
  |/home/peng/.m2/repository/io/dropwizard/metrics/metrics-json/3.1.5/metrics-json-3.1.5.jar	System Classpath
  |/home/peng/.m2/repository/io/dropwizard/metrics/metrics-jvm/3.1.5/metrics-jvm-3.1.5.jar	System Classpath
  |/home/peng/.m2/repository/io/netty/netty-all/4.1.47.Final/netty-all-4.1.47.Final.jar	System Classpath
  |/home/peng/.m2/repository/io/netty/netty/3.9.9.Final/netty-3.9.9.Final.jar	System Classpath
  |/home/peng/.m2/repository/javax/activation/activation/1.1.1/activation-1.1.1.jar	System Classpath
  |/home/peng/.m2/repository/javax/annotation/javax.annotation-api/1.2/javax.annotation-api-1.2.jar	System Classpath
  |/home/peng/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar	System Classpath
  |/home/peng/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar	System Classpath
  |/home/peng/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar	System Classpath
  |/home/peng/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.0.1/javax.ws.rs-api-2.0.1.jar	System Classpath
  |/home/peng/.m2/repository/javax/xml/bind/jaxb-api/2.2.2/jaxb-api-2.2.2.jar	System Classpath
  |/home/peng/.m2/repository/javax/xml/stream/stax-api/1.0-2/stax-api-1.0-2.jar	System Classpath
  |/home/peng/.m2/repository/joda-time/joda-time/2.9.9/joda-time-2.9.9.jar	System Classpath
  |/home/peng/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar	System Classpath
  |/home/peng/.m2/repository/net/razorvine/pyrolite/4.13/pyrolite-4.13.jar	System Classpath
  |/home/peng/.m2/repository/net/sf/opencsv/opencsv/2.3/opencsv-2.3.jar	System Classpath
  |/home/peng/.m2/repository/net/sf/py4j/py4j/0.10.7/py4j-0.10.7.jar	System Classpath
  |/home/peng/.m2/repository/net/sourceforge/f2j/arpack_combined_all/0.1/arpack_combined_all-0.1.jar	System Classpath
  |/home/peng/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.20/nekohtml-1.9.20.jar	System Classpath
  |/home/peng/.m2/repository/oauth/signpost/signpost-core/1.2.1.2/signpost-core-1.2.1.2.jar	System Classpath
  |/home/peng/.m2/repository/org/antlr/antlr4-runtime/4.7/antlr4-runtime-4.7.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/arrow/arrow-format/0.10.0/arrow-format-0.10.0.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/arrow/arrow-memory/0.10.0/arrow-memory-0.10.0.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/arrow/arrow-vector/0.10.0/arrow-vector-0.10.0.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/avro/avro-ipc/1.8.2/avro-ipc-1.8.2.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/avro/avro-mapred/1.8.2/avro-mapred-1.8.2-hadoop2.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/avro/avro/1.8.2/avro-1.8.2.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/commons/commons-compress/1.19/commons-compress-1.19.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/commons/commons-crypto/1.0.0/commons-crypto-1.0.0.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/commons/commons-csv/1.5/commons-csv-1.5.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/commons/commons-math3/3.4.1/commons-math3-3.4.1.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/curator/curator-client/2.6.0/curator-client-2.6.0.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/curator/curator-framework/2.6.0/curator-framework-2.6.0.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/curator/curator-recipes/2.6.0/curator-recipes-2.6.0.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/directory/api/api-asn1-api/1.0.0-M20/api-asn1-api-1.0.0-M20.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/directory/api/api-util/1.0.0-M20/api-util-1.0.0-M20.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/directory/server/apacheds-i18n/2.0.0-M15/apacheds-i18n-2.0.0-M15.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/directory/server/apacheds-kerberos-codec/2.0.0-M15/apacheds-kerberos-codec-2.0.0-M15.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/hadoop/hadoop-annotations/2.6.5/hadoop-annotations-2.6.5.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/hadoop/hadoop-auth/2.6.5/hadoop-auth-2.6.5.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/hadoop/hadoop-client/2.6.5/hadoop-client-2.6.5.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/hadoop/hadoop-common/2.6.5/hadoop-common-2.6.5.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/hadoop/hadoop-hdfs/2.6.5/hadoop-hdfs-2.6.5.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/hadoop/hadoop-mapreduce-client-app/2.6.5/hadoop-mapreduce-client-app-2.6.5.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/hadoop/hadoop-mapreduce-client-common/2.6.5/hadoop-mapreduce-client-common-2.6.5.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/hadoop/hadoop-mapreduce-client-core/2.6.5/hadoop-mapreduce-client-core-2.6.5.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/hadoop/hadoop-mapreduce-client-jobclient/2.6.5/hadoop-mapreduce-client-jobclient-2.6.5.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/hadoop/hadoop-mapreduce-client-shuffle/2.6.5/hadoop-mapreduce-client-shuffle-2.6.5.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/hadoop/hadoop-yarn-api/2.6.5/hadoop-yarn-api-2.6.5.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/hadoop/hadoop-yarn-client/2.6.5/hadoop-yarn-client-2.6.5.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/hadoop/hadoop-yarn-common/2.6.5/hadoop-yarn-common-2.6.5.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/hadoop/hadoop-yarn-server-common/2.6.5/hadoop-yarn-server-common-2.6.5.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/hadoop/hadoop-yarn-server-web-proxy/2.6.5/hadoop-yarn-server-web-proxy-2.6.5.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/httpcomponents/httpclient/4.5.2/httpclient-4.5.2.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/httpcomponents/httpcore/4.4.4/httpcore-4.4.4.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/ivy/ivy/2.4.0/ivy-2.4.0.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/orc/orc-core/1.5.5/orc-core-1.5.5-nohive.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/orc/orc-mapreduce/1.5.5/orc-mapreduce-1.5.5-nohive.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/orc/orc-shims/1.5.5/orc-shims-1.5.5.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/parquet/parquet-column/1.10.1/parquet-column-1.10.1.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/parquet/parquet-common/1.10.1/parquet-common-1.10.1.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/parquet/parquet-encoding/1.10.1/parquet-encoding-1.10.1.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/parquet/parquet-format/2.4.0/parquet-format-2.4.0.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/parquet/parquet-hadoop/1.10.1/parquet-hadoop-1.10.1.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/parquet/parquet-jackson/1.10.1/parquet-jackson-1.10.1.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/pdfbox/fontbox/2.0.16/fontbox-2.0.16.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/pdfbox/pdfbox/2.0.16/pdfbox-2.0.16.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/pdfbox/xmpbox/2.0.16/xmpbox-2.0.16.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/spark/spark-catalyst_2.12/2.4.8/spark-catalyst_2.12-2.4.8.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/spark/spark-core_2.12/2.4.8/spark-core_2.12-2.4.8.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/spark/spark-graphx_2.12/2.4.8/spark-graphx_2.12-2.4.8.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/spark/spark-kvstore_2.12/2.4.8/spark-kvstore_2.12-2.4.8.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/spark/spark-launcher_2.12/2.4.8/spark-launcher_2.12-2.4.8.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/spark/spark-mllib-local_2.12/2.4.8/spark-mllib-local_2.12-2.4.8.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/spark/spark-mllib_2.12/2.4.8/spark-mllib_2.12-2.4.8.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/spark/spark-network-common_2.12/2.4.8/spark-network-common_2.12-2.4.8.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/spark/spark-network-shuffle_2.12/2.4.8/spark-network-shuffle_2.12-2.4.8.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/spark/spark-sketch_2.12/2.4.8/spark-sketch_2.12-2.4.8.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/spark/spark-sql_2.12/2.4.8/spark-sql_2.12-2.4.8.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/spark/spark-streaming_2.12/2.4.8/spark-streaming_2.12-2.4.8.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/spark/spark-tags_2.12/2.4.8/spark-tags_2.12-2.4.8.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/spark/spark-unsafe_2.12/2.4.8/spark-unsafe_2.12-2.4.8.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/spark/spark-yarn_2.12/2.4.8/spark-yarn_2.12-2.4.8.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/tika/tika-core/2.4.0/tika-core-2.4.0.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/xbean/xbean-asm6-shaded/4.8/xbean-asm6-shaded-4.8.jar	System Classpath
  |/home/peng/.m2/repository/org/apache/zookeeper/zookeeper/3.4.6/zookeeper-3.4.6.jar	System Classpath
  |/home/peng/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar	System Classpath
  |/home/peng/.m2/repository/org/codehaus/jackson/jackson-jaxrs/1.9.13/jackson-jaxrs-1.9.13.jar	System Classpath
  |/home/peng/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar	System Classpath
  |/home/peng/.m2/repository/org/codehaus/jackson/jackson-xc/1.9.13/jackson-xc-1.9.13.jar	System Classpath
  |/home/peng/.m2/repository/org/codehaus/janino/commons-compiler/3.0.16/commons-compiler-3.0.16.jar	System Classpath
  |/home/peng/.m2/repository/org/codehaus/janino/janino/3.0.16/janino-3.0.16.jar	System Classpath
  |/home/peng/.m2/repository/org/eclipse/collections/eclipse-collections-api/11.1.0/eclipse-collections-api-11.1.0.jar	System Classpath
  |/home/peng/.m2/repository/org/eclipse/collections/eclipse-collections-forkjoin/11.1.0/eclipse-collections-forkjoin-11.1.0.jar	System Classpath
  |/home/peng/.m2/repository/org/eclipse/collections/eclipse-collections/11.1.0/eclipse-collections-11.1.0.jar	System Classpath
  |/home/peng/.m2/repository/org/fusesource/leveldbjni/leveldbjni-all/1.8/leveldbjni-all-1.8.jar	System Classpath
  |/home/peng/.m2/repository/org/glassfish/hk2/external/aopalliance-repackaged/2.4.0-b34/aopalliance-repackaged-2.4.0-b34.jar	System Classpath
  |/home/peng/.m2/repository/org/glassfish/hk2/external/javax.inject/2.4.0-b34/javax.inject-2.4.0-b34.jar	System Classpath
  |/home/peng/.m2/repository/org/glassfish/hk2/hk2-api/2.4.0-b34/hk2-api-2.4.0-b34.jar	System Classpath
  |/home/peng/.m2/repository/org/glassfish/hk2/hk2-locator/2.4.0-b34/hk2-locator-2.4.0-b34.jar	System Classpath
  |/home/peng/.m2/repository/org/glassfish/hk2/hk2-utils/2.4.0-b34/hk2-utils-2.4.0-b34.jar	System Classpath
  |/home/peng/.m2/repository/org/glassfish/hk2/osgi-resource-locator/1.0.1/osgi-resource-locator-1.0.1.jar	System Classpath
  |/home/peng/.m2/repository/org/glassfish/jersey/bundles/repackaged/jersey-guava/2.22.2/jersey-guava-2.22.2.jar	System Classpath
  |/home/peng/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet-core/2.22.2/jersey-container-servlet-core-2.22.2.jar	System Classpath
  |/home/peng/.m2/repository/org/glassfish/jersey/containers/jersey-container-servlet/2.22.2/jersey-container-servlet-2.22.2.jar	System Classpath
  |/home/peng/.m2/repository/org/glassfish/jersey/core/jersey-client/2.22.2/jersey-client-2.22.2.jar	System Classpath
  |/home/peng/.m2/repository/org/glassfish/jersey/core/jersey-common/2.22.2/jersey-common-2.22.2.jar	System Classpath
  |/home/peng/.m2/repository/org/glassfish/jersey/core/jersey-server/2.22.2/jersey-server-2.22.2.jar	System Classpath
  |/home/peng/.m2/repository/org/glassfish/jersey/media/jersey-media-jaxb/2.22.2/jersey-media-jaxb-2.22.2.jar	System Classpath
  |/home/peng/.m2/repository/org/htrace/htrace-core/3.0.4/htrace-core-3.0.4.jar	System Classpath
  |/home/peng/.m2/repository/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.jar	System Classpath
  |/home/peng/.m2/repository/org/jetbrains/annotations/15.0/annotations-15.0.jar	System Classpath
  |/home/peng/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.2.71/kotlin-stdlib-common-1.2.71.jar	System Classpath
  |/home/peng/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.jar	System Classpath
  |/home/peng/.m2/repository/org/jprocesses/jProcesses/1.6.5/jProcesses-1.6.5.jar	System Classpath
  |/home/peng/.m2/repository/org/json4s/json4s-ast_2.12/3.5.3/json4s-ast_2.12-3.5.3.jar	System Classpath
  |/home/peng/.m2/repository/org/json4s/json4s-core_2.12/3.5.3/json4s-core_2.12-3.5.3.jar	System Classpath
  |/home/peng/.m2/repository/org/json4s/json4s-jackson_2.12/3.5.3/json4s-jackson_2.12-3.5.3.jar	System Classpath
  |/home/peng/.m2/repository/org/json4s/json4s-scalap_2.12/3.5.3/json4s-scalap_2.12-3.5.3.jar	System Classpath
  |/home/peng/.m2/repository/org/jsoup/jsoup/1.11.2/jsoup-1.11.2.jar	System Classpath
  |/home/peng/.m2/repository/org/lz4/lz4-java/1.4.0/lz4-java-1.4.0.jar	System Classpath
  |/home/peng/.m2/repository/org/mapdb/elsa/3.0.0-M5/elsa-3.0.0-M5.jar	System Classpath
  |/home/peng/.m2/repository/org/mapdb/mapdb/3.0.8/mapdb-3.0.8.jar	System Classpath
  |/home/peng/.m2/repository/org/mortbay/jetty/jetty-util/6.1.26/jetty-util-6.1.26.jar	System Classpath
  |/home/peng/.m2/repository/org/mortbay/jetty/jetty/6.1.26/jetty-6.1.26.jar	System Classpath
  |/home/peng/.m2/repository/org/nibor/autolink/autolink/0.6.0/autolink-0.6.0.jar	System Classpath
  |/home/peng/.m2/repository/org/objenesis/objenesis/2.5.1/objenesis-2.5.1.jar	System Classpath
  |/home/peng/.m2/repository/org/ow2/asm/asm-analysis/5.0.3/asm-analysis-5.0.3.jar	System Classpath
  |/home/peng/.m2/repository/org/ow2/asm/asm-tree/5.0.3/asm-tree-5.0.3.jar	System Classpath
  |/home/peng/.m2/repository/org/ow2/asm/asm-util/5.0.3/asm-util-5.0.3.jar	System Classpath
  |/home/peng/.m2/repository/org/ow2/asm/asm/5.0.3/asm-5.0.3.jar	System Classpath
  |/home/peng/.m2/repository/org/parboiled/parboiled-core/1.1.7/parboiled-core-1.1.7.jar	System Classpath
  |/home/peng/.m2/repository/org/parboiled/parboiled-java/1.1.7/parboiled-java-1.1.7.jar	System Classpath
  |/home/peng/.m2/repository/org/pegdown/pegdown/1.6.0/pegdown-1.6.0.jar	System Classpath
  |/home/peng/.m2/repository/org/roaringbitmap/RoaringBitmap/0.7.45/RoaringBitmap-0.7.45.jar	System Classpath
  |/home/peng/.m2/repository/org/roaringbitmap/shims/0.7.45/shims-0.7.45.jar	System Classpath
  |/home/peng/.m2/repository/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.0/scala-parser-combinators_2.12-1.1.0.jar	System Classpath
  |/home/peng/.m2/repository/org/scala-lang/modules/scala-xml_2.12/1.3.0/scala-xml_2.12-1.3.0.jar	System Classpath
  |/home/peng/.m2/repository/org/scala-lang/scala-compiler/2.12.16/scala-compiler-2.12.16.jar	System Classpath
  |/home/peng/.m2/repository/org/scala-lang/scala-library/2.12.16/scala-library-2.12.16.jar	System Classpath
  |/home/peng/.m2/repository/org/scala-lang/scala-reflect/2.12.16/scala-reflect-2.12.16.jar	System Classpath
  |/home/peng/.m2/repository/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar	System Classpath
  |/home/peng/.m2/repository/org/scalacheck/scalacheck_2.12/1.14.0/scalacheck_2.12-1.14.0.jar	System Classpath
  |/home/peng/.m2/repository/org/scalactic/scalactic_2.12/3.2.10/scalactic_2.12-3.2.10.jar	System Classpath
  |/home/peng/.m2/repository/org/scalanlp/breeze-macros_2.12/0.13.2/breeze-macros_2.12-0.13.2.jar	System Classpath
  |/home/peng/.m2/repository/org/scalanlp/breeze_2.12/0.13.2/breeze_2.12-0.13.2.jar	System Classpath
  |/home/peng/.m2/repository/org/scalatest/scalatest-compatible/3.2.10/scalatest-compatible-3.2.10.jar	System Classpath
  |/home/peng/.m2/repository/org/scalatest/scalatest-core_2.12/3.2.10/scalatest-core_2.12-3.2.10.jar	System Classpath
  |/home/peng/.m2/repository/org/scalatest/scalatest-diagrams_2.12/3.2.10/scalatest-diagrams_2.12-3.2.10.jar	System Classpath
  |/home/peng/.m2/repository/org/scalatest/scalatest-featurespec_2.12/3.2.10/scalatest-featurespec_2.12-3.2.10.jar	System Classpath
  |/home/peng/.m2/repository/org/scalatest/scalatest-flatspec_2.12/3.2.10/scalatest-flatspec_2.12-3.2.10.jar	System Classpath
  |/home/peng/.m2/repository/org/scalatest/scalatest-freespec_2.12/3.2.10/scalatest-freespec_2.12-3.2.10.jar	System Classpath
  |/home/peng/.m2/repository/org/scalatest/scalatest-funspec_2.12/3.2.10/scalatest-funspec_2.12-3.2.10.jar	System Classpath
  |/home/peng/.m2/repository/org/scalatest/scalatest-funsuite_2.12/3.2.10/scalatest-funsuite_2.12-3.2.10.jar	System Classpath
  |/home/peng/.m2/repository/org/scalatest/scalatest-matchers-core_2.12/3.2.10/scalatest-matchers-core_2.12-3.2.10.jar	System Classpath
  |/home/peng/.m2/repository/org/scalatest/scalatest-mustmatchers_2.12/3.2.10/scalatest-mustmatchers_2.12-3.2.10.jar	System Classpath
  |/home/peng/.m2/repository/org/scalatest/scalatest-propspec_2.12/3.2.10/scalatest-propspec_2.12-3.2.10.jar	System Classpath
  |/home/peng/.m2/repository/org/scalatest/scalatest-refspec_2.12/3.2.10/scalatest-refspec_2.12-3.2.10.jar	System Classpath
  |/home/peng/.m2/repository/org/scalatest/scalatest-shouldmatchers_2.12/3.2.10/scalatest-shouldmatchers_2.12-3.2.10.jar	System Classpath
  |/home/peng/.m2/repository/org/scalatest/scalatest-wordspec_2.12/3.2.10/scalatest-wordspec_2.12-3.2.10.jar	System Classpath
  |/home/peng/.m2/repository/org/scalatest/scalatest_2.12/3.2.10/scalatest_2.12-3.2.10.jar	System Classpath
  |/home/peng/.m2/repository/org/slf4j/jcl-over-slf4j/1.7.16/jcl-over-slf4j-1.7.16.jar	System Classpath
  |/home/peng/.m2/repository/org/slf4j/jul-to-slf4j/1.7.16/jul-to-slf4j-1.7.16.jar	System Classpath
  |/home/peng/.m2/repository/org/slf4j/slf4j-api/1.7.16/slf4j-api-1.7.16.jar	System Classpath
  |/home/peng/.m2/repository/org/slf4j/slf4j-log4j12/1.7.16/slf4j-log4j12-1.7.16.jar	System Classpath
  |/home/peng/.m2/repository/org/spark-project/spark/unused/1.0.0/unused-1.0.0.jar	System Classpath
  |/home/peng/.m2/repository/org/spire-math/spire-macros_2.12/0.13.0/spire-macros_2.12-0.13.0.jar	System Classpath
  |/home/peng/.m2/repository/org/spire-math/spire_2.12/0.13.0/spire_2.12-0.13.0.jar	System Classpath
  |/home/peng/.m2/repository/org/tukaani/xz/1.5/xz-1.5.jar	System Classpath
  |/home/peng/.m2/repository/org/typelevel/machinist_2.12/0.6.1/machinist_2.12-0.6.1.jar	System Classpath
  |/home/peng/.m2/repository/org/typelevel/macro-compat_2.12/1.1.1/macro-compat_2.12-1.1.1.jar	System Classpath
  |/home/peng/.m2/repository/org/xerial/snappy/snappy-java/1.1.8.2/snappy-java-1.1.8.2.jar	System Classpath
  |/home/peng/.m2/repository/oro/oro/2.0.8/oro-2.0.8.jar	System Classpath
  |/home/peng/.m2/repository/xerces/xercesImpl/2.11.0/xercesImpl-2.11.0.jar	System Classpath
  |/home/peng/.m2/repository/xml-apis/xml-apis/1.4.01/xml-apis-1.4.01.jar	System Classpath
  |/home/peng/.m2/repository/xmlenc/xmlenc/0.52/xmlenc-0.52.jar	System Classpath
  |/home/peng/git-legacy/spookystuff/core/target/classes	System Classpath
  |/home/peng/git-legacy/spookystuff/core/target/test-classes	System Classpath
  |/home/peng/git-legacy/spookystuff/integration/target/test-classes	System Classpath
  |/home/peng/git-legacy/spookystuff/mldsl/target/classes	System Classpath
  |/home/peng/git-legacy/spookystuff/mldsl/target/test-classes	System Classpath
  |/home/peng/git-legacy/spookystuff/test-resources/target/classes	System Classpath
  |/home/peng/git-legacy/spookystuff/web/target/classes	System Classpath
  |/home/shared/jetbrains-toolbox/apps/IDEA-U/ch-0/222.4167.29.plugins/Scala/lib/runners.jar	System Classpath
  |""".stripMargin
    ) {}
