channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - future=0.18.2
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - monotonic=1.5
  - ncurses=6.2
  - openssl=1.1.1i
  - pip=20.3.3
  - pyserial=3.5
  - python=3.9.1
  - python_abi=3.9
  - readline=8.0
  - setuptools=51.0.0
  - simplejson=3.17.2
  - six=1.15.0
  - sqlite=3.34.0
  - tk=8.6.10
  - tzdata=2020d
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - dronekit==2.9.2
    - dronekit-sitl==3.3.0
    - lxml==4.6.2
    - mavproxy==1.8.30
    - psutil==5.8.0
    - pymavlink==2.4.14
